feat/firstrun-1708278357 -- Failed Job

diff --git a/.github/workflows/first-action.yml b/.github/workflows/first-action.yml
--- a/.github/workflows/first-action.yml
+++ b/.github/workflows/first-action.yml
@@ -8,4 +8,12 @@ jobs:
       runs-on:  ubuntu-latest
       steps:
         - name: Say hello
-          run: echo "Hello, World"          
+          run: echo "Hello, World"  
+        
+        - name: Failed step
+          run: |
+            echo "Failed step"
+            exit 1
+        
+        - name: Say goodbye
+          run: echo "GoodBye"
